package com.smartquit.smartquitiot.enums;

public enum HealthRecoveryDataName {
    PULSE_RATE,//
    OXYGEN_LEVEL,//
    CARBON_MONOXIDE_LEVEL,//
    NICOTINE_EXPELLED_FROM_BODY,
    TASTE_AND_SMELL,//
    BREATHING,
    ENERGY_LEVEL,
    TOOTH_STAINING,
    GUMS_AND_TEETH,
    CIRCULATION,//
    GUM_TEXTURE,
    IMMUNITY_AND_LUNG_FUNCTION,
    REDUCED_RISK_OF_HEART_DISEASE,
    DECREASED_RISK_OF_LUNG_CANCER,
    DECREASED_RISK_OF_HEART_ATTACK,
}
